
title: Zhu Xingda's Blog #Your awesome title
email: zhuxingda211@outlook.com
description: > # this means to ignore newlines until "baseurl"
  - 阿雪：那你知道单例模式吗？

baseurl: # the subpath of the site
url: https://zhuxingda.github.io/ # the base hostname & protocol for your site

permalink: /:year-:month/:title
timezone:

favicon: /assets/img/favicon.ico

google_analytics: G-Z1B5BTXMKD
disqus_shortname: #disqus shortname

user:
  name: Zhu Xingda
  pic: /assets/img/guagua.jpeg
  picAlt: "catbook"
  job: student
  message: axue&ada 
  aboutme: true # comment this out if you don't need the 'about' page.

exclude:
  - README.md
  - LICENSE
  - github
  
  
theme_mode: dark

defaults:
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      comment: true   

markdown_ext: "markdown,mkdown,mkdn,mkd,md"
markdown: kramdown 

# Filtering Content
show_drafts: null
limit_posts: 0
future:      false
unpublished: false