title: Blog # name of the site
author: Zhu Xingda # name of site's author
email: zhuxingda211@outlook.com # email of site's author
url: https://zhuxingda.github.io # root address of the site
#baseurl: "/no-style-please" # subpath of the site, e.g. "/blog"
description: > # description of the site (multiple lines allowed)
  朱兴达的个人博客.

permalink: /:slug.html

favicon: "logo.jpg" # name+extension of favicon (which must be put on the root folder)
# goat_counter: "yoursitename" # put your GoatCounter name if you want to use GoatCounter analytics

theme: no-style-please # if you are using GitHub Pages, change it to remote_theme: riggraz/no-style-please

theme_config:
  appearance: "dark" # can be "light", "dark" or "auto"
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: true # show blog description in home page

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag

